[package]
name = "styrdokument2"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
serde = "1.0.219"
time = "0.3.39"
toml = "0.8.20"
typst = "0.13.1"
typst-html = "0.13.1"
typst-pdf = "0.13.1"
